### ISSUE TITLE
Single csv file for complete db

### ISSUE THREAD

**Issue by yokesh-sparkout** [Krishnasony/Import_Export_CSV_File-Android_Kotlin#1]
Is it possible to export as a single csv file for all tables instead of separate csv files for each table ?

**Comment by Krishnasony** [comment]
Yes, It's possible to export all DB tables as CSV files.

Check this post: https://stackoverflow.com/a/31367824/9523118

**Comment by Krishnasony** [comment]
> Is it possible to export as a single CSV file for all tables instead of separate CSV files for each table?

Yes, It's possible to export all DB tables as CSV files.

Check this post: https://stackoverflow.com/a/31367824/9523118
